apiVersion: v1
kind: ConfigMap
metadata:
  name: config-example
data:
  application.properties: |-
    welcome.message=config-map -> message log scheduled
    message=config-map -> message from RestController