apiVersion: v1
kind: ConfigMap
metadata:
  name: config-example
data:
  application.properties: |-
    welcome.message=config-map -> Hello aamv from app.properties
    message=config-map -> Hi from app.properties