apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: aamv-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: aamv-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: aamv-service-account
    namespace: default
roleRef:
  kind: Role
  name: aamv-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aamv-service-account
  namespace: default